apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: author
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        role: author
    spec:
      containers:
      - image: inlet/aem-author
        imagePullPolicy: IfNotPresent
        name: author
        ports:
        - containerPort: 4502
        resources: {}
      restartPolicy: Always
status: {}
