apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: publisher
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        role: publisher
    spec:
      containers:
      - image: inlet/aem-publisher:latest
        imagePullPolicy: IfNotPresent
        name: publisher
        ports:
        - containerPort: 4503
        resources: {}
      restartPolicy: Always
status: {}
